# Configuración de SonarQube Scanner
sonar.projectKey=test-jenkins-cicd
sonar.projectName=Test Jenkins CICD
sonar.projectVersion=1.0.0

# Rutas de código fuente
sonar.sources=src/main/java
sonar.tests=src/test/java

# Exclusiones
sonar.exclusions=**/target/**

# Lenguaje
sonar.language=java

# Cobertura de código (JaCoCo)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml